### ISSUE TITLE
Missing roofline analysis on MI300X

### ISSUE THREAD

**Issue by zjing14** [AMDResearch/omniperf#413] opened 2024-08-16 02:00 UTC
**Describe the bug**
Got the following error message when running roofline analysis on MI300
`Roofline temporarily disabled in MI300`

Looks like the roofline micro-bench for MI300 is missing in `https://github.com/ROCm/omniperf/tree/amd-staging/src/utils/rooflines`

**Development Environment:**
 - Linux Distribution: [RHEL8]
 - Omniperf Version: [2.0.1]
 - GPU: [M300]

**Comment by coleramos425** [comment] 2024-08-16 16:34
Duplicate of issue #285. Let's move the discussion there to keep things simple for tracking purposes.

**Closed as completed by coleramos425** 2024-08-16 16:34 UTC
Labels: bug, duplicate

**Comment by zjing14** [comment] 2024-08-16 18:58
@coleramos425 Thanks.
